version: "3"
services:
  db:
    image: "container-registry.oracle.com/database/free:latest"
    environment:
      - ORACLE_PWD=12345678SecurePassword
    volumes:
      - ./data:/opt/oracle/oradata
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    