version: "3"
services:
  db:
    image: "container-registry.oracle.com/database/free:latest"
    env_file: .env
    environment:
      - ORACLE_PWD=${DATABASE_PASSWORD}
    volumes:
      - ./db-data:/opt/oracle/oradata
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 80:8000
    restart: unless-stopped